version: "3"
services:
  db:
    image: mysql:8.4.3
    env_file:
      - .env
    restart: unless-stopped
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: aawaj1234
      MYSQL_DATABASE: aawaj
      MYSQL_USER: aawaj_user
      MYSQL_PASSWORD: aawaj123
    volumes:
      - ../mysql-data:/var/lib/mysql
    ports:
      - 3307:3306

  # web:
  #   build: .
  #   container_name: backend
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/var/www/html
  #   depends_on:
  #     - db
  #   ports:
  #     - 8001:80

volumes:
  db: