name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete --exclude '.env'
        path: /
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host:  ${{ secrets.DEPLOY_HOST }}
        remote_user:  ${{ secrets.DEPLOY_USER }}
        remote_password:  ${{ secrets.DEPLOY_PASSKEY }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
        remote_key_pass: ${{ secrets.DEPLOY_PASSKEY }}
